name: jraadpsenv
channels:
  - conda-forge

dependencies:
  - python=3.11
  - python-dotenv
  - pytorch
  - torchvision
  - cupy
  - parallelproj
  - numpy
  - pywavelets
  - pyyaml
  - tensorboard
  - torchio
